# HANDS-ON 1

### Task 1- Import Numpy

In [1]:
import numpy as np

In [2]:
# This means NumPy has been successfully imported and is ready to use.

### Task 2- Create your Array

In [3]:
temperatures= [27.5, 29.0, 28.5]
temperature_array= np.array(temperatures)

temperature_array

array([27.5, 29. , 28.5])

### Task 3- Inspect the Data Type

In [4]:
temperature_array.dtype

dtype('float64')

### Task 4- Create a 2D Array

In [5]:
weather_data=[
    [27.5, 28.0, 29.5],
    [28.0, 29.0, 30.0]
]

weather_array= np.array(weather_data)
weather_array

array([[27.5, 28. , 29.5],
       [28. , 29. , 30. ]])

In [6]:
# 1. Is it 1D or 2D? : it is a 2D because there is a list inside another list.

# 2. Is it a vector or matrix? : it is a Matrix because A 2D NumPy array is commonly described as a matrix.

# 3. How many rows? : 2 rows because You can see two inner lists:

# [27.5, 28.0, 29.5]  ← Row 1
# [28.0, 29.0, 30.0]  ← Row 2

# 4. How many values are in each row? : 3 values. So the array has a shape of 2 × 3.

# HANDS-ON 2 

### Task 1- Try It With Python Lists

In [7]:
sales_timothy = [10, 15, 20]
sales_brenda = [5, 10, 15]

sales_timothy + sales_brenda

[10, 15, 20, 5, 10, 15]

In [8]:
# 1. No, Python did not produce [15, 25, 35].
# 2. Python joined the two lists together.
# 3. The + operator concatenates Python lists instead of performing element-by-element addition.

### Task 2- Convert Them to NumPy Arrays

In [9]:
sales_timothy = [10, 15, 20]
sales_brenda = [5, 10, 15]

timothy_array = np.array(sales_timothy)
brenda_array = np.array(sales_brenda)

timothy_array + brenda_array

array([15, 25, 35])

### Task 3- Compare the Results

In [10]:
# Python lists: [10, 15, 20] + [5, 10, 15] = [10, 15, 20, 5, 10, 15]
# NumPy arrays: [10, 15, 20] + [5, 10, 15] = [15, 25, 35]


# NumPy is useful because it allows us to perform numerical operations
# element by element across arrays, making it easier to analyze and
# manipulate numerical data.

### Challenge- Five Days of Sales

In [11]:
online_sales = np.array([20, 25, 30, 35, 40])
store_sales = np.array([15, 20, 25, 30, 35])

combined_sales = online_sales + store_sales
difference = online_sales - store_sales

print("Combined sales:", combined_sales)
print("Difference:", difference)

Combined sales: [35 45 55 65 75]
Difference: [5 5 5 5 5]


# HANDS-ON 3

### Part 1- Create the Dataset

In [12]:
temperatures = [27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]

temperature_array = np.array(temperatures)

temperature_array

array([27.5, 29. , 30.5, 28. , 31. , 32.5, 30. ])

### Part 2- Understand Your Array

In [13]:
print("Number of dimensions:", temperature_array.ndim)
print("Shape:", temperature_array.shape)
print("Data type:", temperature_array.dtype)
print("Number of observations:", temperature_array.size)

Number of dimensions: 1
Shape: (7,)
Data type: float64
Number of observations: 7


In [14]:
# Therefore, it is a 1D array, and a 1D NumPy array is commonly described as a vector.
# This also means that it is a one dimension containing 7 values. 
# The data type is float64 and there are 7 temperature observations.

### Part 3- Perform Numerical Operations

In [19]:
# create the target array
target = [28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0]

target_array = np.array(target)

print("Target Array:",target_array)

# Temperature Difference
temperature_difference = temperature_array - target_array

print("Temperature Difference:",temperature_difference)

# Increase Every Temperature by 2°C
increased_temperatures = temperature_array + 2

increased_temperatures
print("Increased Temperature:",increased_temperatures)

Target Array: [28. 28. 29. 28. 30. 30. 29.]
Temperature Difference: [-0.5  1.   1.5  0.   1.   2.5  1. ]
Increased Temperature: [29.5 31.  32.5 30.  33.  34.5 32. ]


### Part 4- Think Like an Analyst

In [25]:
 # Which day appears to have the highest recorded temperature?
temperature_array.max()
temperature_array.argmax()
print("Highest Temperature:",temperature_array.max())
print("Position of Highest Temperature:",temperature_array.argmax())

# On which days was the recorded temperature above the target?
# True means the recorded temperature was above the target.
temperature_array > target_array
print("Days above the Target:",temperature_array > target_array)

# What does the temperature difference tell the weather-monitoring team?.

Highest Temperature: 32.5
Position of Highest Temperature: 5
Days above the Target: [False  True  True False  True  True  True]


### What does the temperature difference tell the weather-monitoring team?

The temperature difference shows how much the recorded temperature was above or below the target temperature for each day. A positive value means the recorded temperature was above the target, a negative value means it was below the target, and zero means it matched the target.


### Why would using a NumPy array be more convenient than keeping the temperatures only as a Python list?
NumPy arrays make numerical analysis more convenient because mathematical operations can be performed directly on all the values element by element. This makes it easy to calculate differences, increase values, compare data, and perform other numerical operations without manually processing each value with a loop.

# MINI PROJECT: Weather Temperature Analysis Using NumPy

### Project Introduction

This project analyzes temperature data collected from three weather-monitoring
locations: Lagos, Abuja, and Ibadan. NumPy is used to convert the raw Python
lists into numerical arrays and perform calculations and comparisons.
The analysis will identify the location with the highest temperature on each
day, calculate temperatures after a 1°C increase, and compare temperature
readings between Lagos and Abuja.

### Dataset

The weather station recorded temperatures for five days at three locations:
Lagos, Abuja, and Ibadan.

All temperatures are measured in degrees Celsius (°C).

In [26]:
lagos = [27.5, 29.0, 30.5, 28.0, 31.0]

abuja = [25.0, 28.0, 29.5, 30.0, 32.0]

ibadan = [26.5, 28.5, 29.0, 27.5, 30.5]

lagos_array = np.array(lagos)

abuja_array = np.array(abuja)

ibadan_array = np.array(ibadan)


print("Lagos:", lagos_array)
print("Abuja:", abuja_array)
print("Ibadan:", ibadan_array)

Lagos: [27.5 29.  30.5 28.  31. ]
Abuja: [25.  28.  29.5 30.  32. ]
Ibadan: [26.5 28.5 29.  27.5 30.5]


In [28]:
# Array Inspection
print("Lagos dimensions:", lagos_array.ndim)
print("Lagos shape:", lagos_array.shape)
print("Lagos data type:", lagos_array.dtype)
print("Number of Lagos observations:", lagos_array.size)
print()
print("Abuja dimensions:", abuja_array.ndim)
print("Abuja shape:", abuja_array.shape)
print("Abuja data type:", abuja_array.dtype)
print("Number of Abuja observations:", abuja_array.size)
print()
print("Ibadan dimensions:", ibadan_array.ndim)
print("Ibadan shape:", ibadan_array.shape)
print("Ibadan data type:", ibadan_array.dtype)
print("Number of Ibadan observations:", ibadan_array.size)

Lagos dimensions: 1
Lagos shape: (5,)
Lagos data type: float64
Number of Lagos observations: 5

Abuja dimensions: 1
Abuja shape: (5,)
Abuja data type: float64
Number of Abuja observations: 5

Ibadan dimensions: 1
Ibadan shape: (5,)
Ibadan data type: float64
Number of Ibadan observations: 5


In [29]:
# Challenge 1 — Find the Highest Temperature on Each Day
all_temperatures = np.array([
    lagos_array,
    abuja_array,
    ibadan_array
])

print ("All Temperatures:",all_temperatures)

highest_each_day = np.max(all_temperatures, axis=0)
print("Highest Temperature for each day:",highest_each_day)


highest_location_index = np.argmax(all_temperatures, axis=0)
print("Highest Location:",highest_location_index)

# axis=0 tells NumPy to compare the values down each column

All Temperatures: [[27.5 29.  30.5 28.  31. ]
 [25.  28.  29.5 30.  32. ]
 [26.5 28.5 29.  27.5 30.5]]
Highest Temperature for each day: [27.5 29.  30.5 30.  32. ]
Highest Location: [0 0 0 1 1]


In [30]:
# Challenge 2 — Increase Every Temperature by 1°C
lagos_plus_1 = lagos_array + 1
abuja_plus_1 = abuja_array + 1
ibadan_plus_1 = ibadan_array + 1

print("Lagos after +1°C:", lagos_plus_1)
print("Abuja after +1°C:", abuja_plus_1)
print("Ibadan after +1°C:", ibadan_plus_1)

Lagos after +1°C: [28.5 30.  31.5 29.  32. ]
Abuja after +1°C: [26.  29.  30.5 31.  33. ]
Ibadan after +1°C: [27.5 29.5 30.  28.5 31.5]


In [32]:
#Challenge 3 — Compare Lagos With Abuja
lagos_abuja_difference = lagos_array - abuja_array

print("Lagos-Abuja Difference:",lagos_abuja_difference)

lagos_array > abuja_array

#Lagos vs Abuja Comparison :The temperature difference was calculated by subtracting Abuja's temperature from Lagos' temperature for each day.
#A positive difference means Lagos was warmer than Abuja, while a negative difference means Lagos was cooler than Abuja.

Lagos-Abuja Difference: [ 2.5  1.   1.  -2.  -1. ]


array([ True,  True,  True, False, False])

### Findings

1. The temperature data shows that Lagos recorded the highest temperature on
   Days 1, 2, and 3, while Abuja recorded the highest temperature on Days 4
   and 5.

2. Abuja recorded the highest temperature in the dataset, reaching 32.0°C on
   Day 5.

3. Lagos was warmer than Abuja on Days 1, 2, and 3, but Abuja was warmer than
   Lagos on Days 4 and 5.

4. The largest temperature difference between Lagos and Abuja occurred on
   Day 1, when Lagos was 2.5°C warmer than Abuja.

5. Adding 1°C to the arrays demonstrates that NumPy can perform the same
   numerical operation on every element without requiring a for loop.

## Conclusion

This project demonstrated how NumPy can be used to convert weather data from
Python lists into numerical arrays and perform useful numerical analysis.
The arrays made it possible to compare temperatures across different
locations, identify the highest temperature for each day, calculate
temperature differences, and increase all readings by 1°C without manually
processing each value.

As the amount of numerical data increases, NumPy becomes increasingly useful
because it allows calculations and comparisons to be performed efficiently
across entire arrays. This makes numerical data easier to analyze and
interpret.#

# BONUS CHALLENGE

### My Predictions

Given:

x = [2, 4, 6]

y = [1, 3, 5]

For x + y, I predict:
[3, 7, 11]

For x - y, I predict:
[1, 1, 1]

For x * y, I predict:
[2, 12, 30]

In [33]:
x = np.array([2, 4, 6])
y = np.array([1, 3, 5])

print(x + y)
print(x - y)
print(x * y)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


### I learned that NumPy arrays perform arithmetic operations element by element. When two arrays have the same shape, corresponding values are added, subtracted, or multiplied with each other.